settings:
  title: 'Skindow Status Page'
  url: 'https://cf-status.skindow.xyz/' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 30 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: chat-next-web.skindow.xyz # unique identifier
    name: chat-next-web.skindow.xyz
    description: 'chat gpt next status' # default=empty
    url: 'https://chat-next-web.skindow.xyz/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: gptnext.skindow.xyzhttps://coze-proxy.skindow.xyz/
    name: gptnext.skindow.xyz
    description: 'gpt next web'
    url: 'https://gptnext.skindow.xyz/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: coze-proxy.skindow.xyz
    name: coze-proxy.skindow.xyz
    description: 'coze discord proxy'
    url: 'https://coze-proxy.skindow.xyz'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
    followRedirect: true # should fetch follow redirects, default=false

  - id: warp-clash-api.skindow.xyz
    name: warp-clash-api.skindow.xyz
    description: 'warp-clash-api'
    url: 'https://warp-clash-api.skindow.xyz'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
    
  - id: librechat.skindow.xyz
    name: librechat.skindow.xyz
    description: 'librechat'
    url: 'https://librechat.skindow.xyz'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

   

